/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CoachRouteImport } from './routes/_coach'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CoachLoginRouteImport } from './routes/coach.login'
import { Route as CoachSettingsRouteImport } from './routes/_coach/settings'
import { Route as CoachCoachRouteImport } from './routes/_coach/coach'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedGuideRouteImport } from './routes/_authenticated/guide'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCycleRouteImport } from './routes/_authenticated/cycle'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedReportSessionIdRouteImport } from './routes/_authenticated/report.$sessionId'
import { Route as AuthenticatedPrintAllRouteImport } from './routes/_authenticated/print.all'
import { Route as AuthenticatedGuideSection9RouteImport } from './routes/_authenticated/guide.section-9'
import { Route as AuthenticatedGuideSection8RouteImport } from './routes/_authenticated/guide.section-8'
import { Route as AuthenticatedGuideSection7RouteImport } from './routes/_authenticated/guide.section-7'
import { Route as AuthenticatedGuideSection6RouteImport } from './routes/_authenticated/guide.section-6'
import { Route as AuthenticatedGuideSection5RouteImport } from './routes/_authenticated/guide.section-5'
import { Route as AuthenticatedGuideSection4RouteImport } from './routes/_authenticated/guide.section-4'
import { Route as AuthenticatedGuideSection3RouteImport } from './routes/_authenticated/guide.section-3'
import { Route as AuthenticatedGuideSection2RouteImport } from './routes/_authenticated/guide.section-2'
import { Route as AuthenticatedGuideSection12RouteImport } from './routes/_authenticated/guide.section-12'
import { Route as AuthenticatedGuideSection11RouteImport } from './routes/_authenticated/guide.section-11'
import { Route as AuthenticatedGuideSection10RouteImport } from './routes/_authenticated/guide.section-10'
import { Route as AuthenticatedGuideSection1RouteImport } from './routes/_authenticated/guide.section-1'
import { Route as AuthenticatedCheckoutActivatingRouteImport } from './routes/_authenticated/checkout.activating'
import { Route as AuthenticatedAssessmentTypeRouteImport } from './routes/_authenticated/assessment.$type'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as CoachCoachAssesseeUserIdRouteImport } from './routes/_coach/coach.assessee.$userId'
import { Route as AuthenticatedPrintSectionNumberRouteImport } from './routes/_authenticated/print.section.$number'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/_coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachLoginRoute = CoachLoginRouteImport.update({
  id: '/coach/login',
  path: '/coach/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachSettingsRoute = CoachSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CoachRoute,
} as any)
const CoachCoachRoute = CoachCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => CoachRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGuideRoute = AuthenticatedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCycleRoute = AuthenticatedCycleRouteImport.update({
  id: '/cycle',
  path: '/cycle',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportSessionIdRoute =
  AuthenticatedReportSessionIdRouteImport.update({
    id: '/report/$sessionId',
    path: '/report/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPrintAllRoute = AuthenticatedPrintAllRouteImport.update({
  id: '/print/all',
  path: '/print/all',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuideSection9Route =
  AuthenticatedGuideSection9RouteImport.update({
    id: '/section-9',
    path: '/section-9',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedGuideSection8Route =
  AuthenticatedGuideSection8RouteImport.update({
    id: '/section-8',
    path: '/section-8',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedGuideSection7Route =
  AuthenticatedGuideSection7RouteImport.update({
    id: '/section-7',
    path: '/section-7',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedGuideSection6Route =
  AuthenticatedGuideSection6RouteImport.update({
    id: '/section-6',
    path: '/section-6',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedGuideSection5Route =
  AuthenticatedGuideSection5RouteImport.update({
    id: '/section-5',
    path: '/section-5',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedGuideSection4Route =
  AuthenticatedGuideSection4RouteImport.update({
    id: '/section-4',
    path: '/section-4',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedGuideSection3Route =
  AuthenticatedGuideSection3RouteImport.update({
    id: '/section-3',
    path: '/section-3',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedGuideSection2Route =
  AuthenticatedGuideSection2RouteImport.update({
    id: '/section-2',
    path: '/section-2',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedGuideSection12Route =
  AuthenticatedGuideSection12RouteImport.update({
    id: '/section-12',
    path: '/section-12',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedGuideSection11Route =
  AuthenticatedGuideSection11RouteImport.update({
    id: '/section-11',
    path: '/section-11',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedGuideSection10Route =
  AuthenticatedGuideSection10RouteImport.update({
    id: '/section-10',
    path: '/section-10',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedGuideSection1Route =
  AuthenticatedGuideSection1RouteImport.update({
    id: '/section-1',
    path: '/section-1',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedCheckoutActivatingRoute =
  AuthenticatedCheckoutActivatingRouteImport.update({
    id: '/checkout/activating',
    path: '/checkout/activating',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssessmentTypeRoute =
  AuthenticatedAssessmentTypeRouteImport.update({
    id: '/assessment/$type',
    path: '/assessment/$type',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoachCoachAssesseeUserIdRoute =
  CoachCoachAssesseeUserIdRouteImport.update({
    id: '/assessee/$userId',
    path: '/assessee/$userId',
    getParentRoute: () => CoachCoachRoute,
  } as any)
const AuthenticatedPrintSectionNumberRoute =
  AuthenticatedPrintSectionNumberRouteImport.update({
    id: '/print/section/$number',
    path: '/print/section/$number',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/cycle': typeof AuthenticatedCycleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guide': typeof AuthenticatedGuideRouteWithChildren
  '/performance': typeof AuthenticatedPerformanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/coach': typeof CoachCoachRouteWithChildren
  '/settings': typeof CoachSettingsRoute
  '/coach/login': typeof CoachLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/assessment/$type': typeof AuthenticatedAssessmentTypeRoute
  '/checkout/activating': typeof AuthenticatedCheckoutActivatingRoute
  '/guide/section-1': typeof AuthenticatedGuideSection1Route
  '/guide/section-10': typeof AuthenticatedGuideSection10Route
  '/guide/section-11': typeof AuthenticatedGuideSection11Route
  '/guide/section-12': typeof AuthenticatedGuideSection12Route
  '/guide/section-2': typeof AuthenticatedGuideSection2Route
  '/guide/section-3': typeof AuthenticatedGuideSection3Route
  '/guide/section-4': typeof AuthenticatedGuideSection4Route
  '/guide/section-5': typeof AuthenticatedGuideSection5Route
  '/guide/section-6': typeof AuthenticatedGuideSection6Route
  '/guide/section-7': typeof AuthenticatedGuideSection7Route
  '/guide/section-8': typeof AuthenticatedGuideSection8Route
  '/guide/section-9': typeof AuthenticatedGuideSection9Route
  '/print/all': typeof AuthenticatedPrintAllRoute
  '/report/$sessionId': typeof AuthenticatedReportSessionIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/print/section/$number': typeof AuthenticatedPrintSectionNumberRoute
  '/coach/assessee/$userId': typeof CoachCoachAssesseeUserIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/cycle': typeof AuthenticatedCycleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guide': typeof AuthenticatedGuideRouteWithChildren
  '/performance': typeof AuthenticatedPerformanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/coach': typeof CoachCoachRouteWithChildren
  '/settings': typeof CoachSettingsRoute
  '/coach/login': typeof CoachLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/assessment/$type': typeof AuthenticatedAssessmentTypeRoute
  '/checkout/activating': typeof AuthenticatedCheckoutActivatingRoute
  '/guide/section-1': typeof AuthenticatedGuideSection1Route
  '/guide/section-10': typeof AuthenticatedGuideSection10Route
  '/guide/section-11': typeof AuthenticatedGuideSection11Route
  '/guide/section-12': typeof AuthenticatedGuideSection12Route
  '/guide/section-2': typeof AuthenticatedGuideSection2Route
  '/guide/section-3': typeof AuthenticatedGuideSection3Route
  '/guide/section-4': typeof AuthenticatedGuideSection4Route
  '/guide/section-5': typeof AuthenticatedGuideSection5Route
  '/guide/section-6': typeof AuthenticatedGuideSection6Route
  '/guide/section-7': typeof AuthenticatedGuideSection7Route
  '/guide/section-8': typeof AuthenticatedGuideSection8Route
  '/guide/section-9': typeof AuthenticatedGuideSection9Route
  '/print/all': typeof AuthenticatedPrintAllRoute
  '/report/$sessionId': typeof AuthenticatedReportSessionIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/print/section/$number': typeof AuthenticatedPrintSectionNumberRoute
  '/coach/assessee/$userId': typeof CoachCoachAssesseeUserIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_coach': typeof CoachRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/cycle': typeof AuthenticatedCycleRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/guide': typeof AuthenticatedGuideRouteWithChildren
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_coach/coach': typeof CoachCoachRouteWithChildren
  '/_coach/settings': typeof CoachSettingsRoute
  '/coach/login': typeof CoachLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/assessment/$type': typeof AuthenticatedAssessmentTypeRoute
  '/_authenticated/checkout/activating': typeof AuthenticatedCheckoutActivatingRoute
  '/_authenticated/guide/section-1': typeof AuthenticatedGuideSection1Route
  '/_authenticated/guide/section-10': typeof AuthenticatedGuideSection10Route
  '/_authenticated/guide/section-11': typeof AuthenticatedGuideSection11Route
  '/_authenticated/guide/section-12': typeof AuthenticatedGuideSection12Route
  '/_authenticated/guide/section-2': typeof AuthenticatedGuideSection2Route
  '/_authenticated/guide/section-3': typeof AuthenticatedGuideSection3Route
  '/_authenticated/guide/section-4': typeof AuthenticatedGuideSection4Route
  '/_authenticated/guide/section-5': typeof AuthenticatedGuideSection5Route
  '/_authenticated/guide/section-6': typeof AuthenticatedGuideSection6Route
  '/_authenticated/guide/section-7': typeof AuthenticatedGuideSection7Route
  '/_authenticated/guide/section-8': typeof AuthenticatedGuideSection8Route
  '/_authenticated/guide/section-9': typeof AuthenticatedGuideSection9Route
  '/_authenticated/print/all': typeof AuthenticatedPrintAllRoute
  '/_authenticated/report/$sessionId': typeof AuthenticatedReportSessionIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/print/section/$number': typeof AuthenticatedPrintSectionNumberRoute
  '/_coach/coach/assessee/$userId': typeof CoachCoachAssesseeUserIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/cycle'
    | '/dashboard'
    | '/guide'
    | '/performance'
    | '/profile'
    | '/coach'
    | '/settings'
    | '/coach/login'
    | '/email/unsubscribe'
    | '/assessment/$type'
    | '/checkout/activating'
    | '/guide/section-1'
    | '/guide/section-10'
    | '/guide/section-11'
    | '/guide/section-12'
    | '/guide/section-2'
    | '/guide/section-3'
    | '/guide/section-4'
    | '/guide/section-5'
    | '/guide/section-6'
    | '/guide/section-7'
    | '/guide/section-8'
    | '/guide/section-9'
    | '/print/all'
    | '/report/$sessionId'
    | '/lovable/email/suppression'
    | '/print/section/$number'
    | '/coach/assessee/$userId'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/cycle'
    | '/dashboard'
    | '/guide'
    | '/performance'
    | '/profile'
    | '/coach'
    | '/settings'
    | '/coach/login'
    | '/email/unsubscribe'
    | '/assessment/$type'
    | '/checkout/activating'
    | '/guide/section-1'
    | '/guide/section-10'
    | '/guide/section-11'
    | '/guide/section-12'
    | '/guide/section-2'
    | '/guide/section-3'
    | '/guide/section-4'
    | '/guide/section-5'
    | '/guide/section-6'
    | '/guide/section-7'
    | '/guide/section-8'
    | '/guide/section-9'
    | '/print/all'
    | '/report/$sessionId'
    | '/lovable/email/suppression'
    | '/print/section/$number'
    | '/coach/assessee/$userId'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_coach'
    | '/forgot-password'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/_authenticated/cycle'
    | '/_authenticated/dashboard'
    | '/_authenticated/guide'
    | '/_authenticated/performance'
    | '/_authenticated/profile'
    | '/_coach/coach'
    | '/_coach/settings'
    | '/coach/login'
    | '/email/unsubscribe'
    | '/_authenticated/assessment/$type'
    | '/_authenticated/checkout/activating'
    | '/_authenticated/guide/section-1'
    | '/_authenticated/guide/section-10'
    | '/_authenticated/guide/section-11'
    | '/_authenticated/guide/section-12'
    | '/_authenticated/guide/section-2'
    | '/_authenticated/guide/section-3'
    | '/_authenticated/guide/section-4'
    | '/_authenticated/guide/section-5'
    | '/_authenticated/guide/section-6'
    | '/_authenticated/guide/section-7'
    | '/_authenticated/guide/section-8'
    | '/_authenticated/guide/section-9'
    | '/_authenticated/print/all'
    | '/_authenticated/report/$sessionId'
    | '/lovable/email/suppression'
    | '/_authenticated/print/section/$number'
    | '/_coach/coach/assessee/$userId'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CoachRoute: typeof CoachRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  CoachLoginRoute: typeof CoachLoginRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_coach': {
      id: '/_coach'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/login': {
      id: '/coach/login'
      path: '/coach/login'
      fullPath: '/coach/login'
      preLoaderRoute: typeof CoachLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_coach/settings': {
      id: '/_coach/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof CoachSettingsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/_coach/coach': {
      id: '/_coach/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachCoachRouteImport
      parentRoute: typeof CoachRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guide': {
      id: '/_authenticated/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthenticatedGuideRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cycle': {
      id: '/_authenticated/cycle'
      path: '/cycle'
      fullPath: '/cycle'
      preLoaderRoute: typeof AuthenticatedCycleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/report/$sessionId': {
      id: '/_authenticated/report/$sessionId'
      path: '/report/$sessionId'
      fullPath: '/report/$sessionId'
      preLoaderRoute: typeof AuthenticatedReportSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/print/all': {
      id: '/_authenticated/print/all'
      path: '/print/all'
      fullPath: '/print/all'
      preLoaderRoute: typeof AuthenticatedPrintAllRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guide/section-9': {
      id: '/_authenticated/guide/section-9'
      path: '/section-9'
      fullPath: '/guide/section-9'
      preLoaderRoute: typeof AuthenticatedGuideSection9RouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/section-8': {
      id: '/_authenticated/guide/section-8'
      path: '/section-8'
      fullPath: '/guide/section-8'
      preLoaderRoute: typeof AuthenticatedGuideSection8RouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/section-7': {
      id: '/_authenticated/guide/section-7'
      path: '/section-7'
      fullPath: '/guide/section-7'
      preLoaderRoute: typeof AuthenticatedGuideSection7RouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/section-6': {
      id: '/_authenticated/guide/section-6'
      path: '/section-6'
      fullPath: '/guide/section-6'
      preLoaderRoute: typeof AuthenticatedGuideSection6RouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/section-5': {
      id: '/_authenticated/guide/section-5'
      path: '/section-5'
      fullPath: '/guide/section-5'
      preLoaderRoute: typeof AuthenticatedGuideSection5RouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/section-4': {
      id: '/_authenticated/guide/section-4'
      path: '/section-4'
      fullPath: '/guide/section-4'
      preLoaderRoute: typeof AuthenticatedGuideSection4RouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/section-3': {
      id: '/_authenticated/guide/section-3'
      path: '/section-3'
      fullPath: '/guide/section-3'
      preLoaderRoute: typeof AuthenticatedGuideSection3RouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/section-2': {
      id: '/_authenticated/guide/section-2'
      path: '/section-2'
      fullPath: '/guide/section-2'
      preLoaderRoute: typeof AuthenticatedGuideSection2RouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/section-12': {
      id: '/_authenticated/guide/section-12'
      path: '/section-12'
      fullPath: '/guide/section-12'
      preLoaderRoute: typeof AuthenticatedGuideSection12RouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/section-11': {
      id: '/_authenticated/guide/section-11'
      path: '/section-11'
      fullPath: '/guide/section-11'
      preLoaderRoute: typeof AuthenticatedGuideSection11RouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/section-10': {
      id: '/_authenticated/guide/section-10'
      path: '/section-10'
      fullPath: '/guide/section-10'
      preLoaderRoute: typeof AuthenticatedGuideSection10RouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/section-1': {
      id: '/_authenticated/guide/section-1'
      path: '/section-1'
      fullPath: '/guide/section-1'
      preLoaderRoute: typeof AuthenticatedGuideSection1RouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/checkout/activating': {
      id: '/_authenticated/checkout/activating'
      path: '/checkout/activating'
      fullPath: '/checkout/activating'
      preLoaderRoute: typeof AuthenticatedCheckoutActivatingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assessment/$type': {
      id: '/_authenticated/assessment/$type'
      path: '/assessment/$type'
      fullPath: '/assessment/$type'
      preLoaderRoute: typeof AuthenticatedAssessmentTypeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_coach/coach/assessee/$userId': {
      id: '/_coach/coach/assessee/$userId'
      path: '/assessee/$userId'
      fullPath: '/coach/assessee/$userId'
      preLoaderRoute: typeof CoachCoachAssesseeUserIdRouteImport
      parentRoute: typeof CoachCoachRoute
    }
    '/_authenticated/print/section/$number': {
      id: '/_authenticated/print/section/$number'
      path: '/print/section/$number'
      fullPath: '/print/section/$number'
      preLoaderRoute: typeof AuthenticatedPrintSectionNumberRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedGuideRouteChildren {
  AuthenticatedGuideSection1Route: typeof AuthenticatedGuideSection1Route
  AuthenticatedGuideSection10Route: typeof AuthenticatedGuideSection10Route
  AuthenticatedGuideSection11Route: typeof AuthenticatedGuideSection11Route
  AuthenticatedGuideSection12Route: typeof AuthenticatedGuideSection12Route
  AuthenticatedGuideSection2Route: typeof AuthenticatedGuideSection2Route
  AuthenticatedGuideSection3Route: typeof AuthenticatedGuideSection3Route
  AuthenticatedGuideSection4Route: typeof AuthenticatedGuideSection4Route
  AuthenticatedGuideSection5Route: typeof AuthenticatedGuideSection5Route
  AuthenticatedGuideSection6Route: typeof AuthenticatedGuideSection6Route
  AuthenticatedGuideSection7Route: typeof AuthenticatedGuideSection7Route
  AuthenticatedGuideSection8Route: typeof AuthenticatedGuideSection8Route
  AuthenticatedGuideSection9Route: typeof AuthenticatedGuideSection9Route
}

const AuthenticatedGuideRouteChildren: AuthenticatedGuideRouteChildren = {
  AuthenticatedGuideSection1Route: AuthenticatedGuideSection1Route,
  AuthenticatedGuideSection10Route: AuthenticatedGuideSection10Route,
  AuthenticatedGuideSection11Route: AuthenticatedGuideSection11Route,
  AuthenticatedGuideSection12Route: AuthenticatedGuideSection12Route,
  AuthenticatedGuideSection2Route: AuthenticatedGuideSection2Route,
  AuthenticatedGuideSection3Route: AuthenticatedGuideSection3Route,
  AuthenticatedGuideSection4Route: AuthenticatedGuideSection4Route,
  AuthenticatedGuideSection5Route: AuthenticatedGuideSection5Route,
  AuthenticatedGuideSection6Route: AuthenticatedGuideSection6Route,
  AuthenticatedGuideSection7Route: AuthenticatedGuideSection7Route,
  AuthenticatedGuideSection8Route: AuthenticatedGuideSection8Route,
  AuthenticatedGuideSection9Route: AuthenticatedGuideSection9Route,
}

const AuthenticatedGuideRouteWithChildren =
  AuthenticatedGuideRoute._addFileChildren(AuthenticatedGuideRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCycleRoute: typeof AuthenticatedCycleRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGuideRoute: typeof AuthenticatedGuideRouteWithChildren
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAssessmentTypeRoute: typeof AuthenticatedAssessmentTypeRoute
  AuthenticatedCheckoutActivatingRoute: typeof AuthenticatedCheckoutActivatingRoute
  AuthenticatedPrintAllRoute: typeof AuthenticatedPrintAllRoute
  AuthenticatedReportSessionIdRoute: typeof AuthenticatedReportSessionIdRoute
  AuthenticatedPrintSectionNumberRoute: typeof AuthenticatedPrintSectionNumberRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCycleRoute: AuthenticatedCycleRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGuideRoute: AuthenticatedGuideRouteWithChildren,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAssessmentTypeRoute: AuthenticatedAssessmentTypeRoute,
  AuthenticatedCheckoutActivatingRoute: AuthenticatedCheckoutActivatingRoute,
  AuthenticatedPrintAllRoute: AuthenticatedPrintAllRoute,
  AuthenticatedReportSessionIdRoute: AuthenticatedReportSessionIdRoute,
  AuthenticatedPrintSectionNumberRoute: AuthenticatedPrintSectionNumberRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CoachCoachRouteChildren {
  CoachCoachAssesseeUserIdRoute: typeof CoachCoachAssesseeUserIdRoute
}

const CoachCoachRouteChildren: CoachCoachRouteChildren = {
  CoachCoachAssesseeUserIdRoute: CoachCoachAssesseeUserIdRoute,
}

const CoachCoachRouteWithChildren = CoachCoachRoute._addFileChildren(
  CoachCoachRouteChildren,
)

interface CoachRouteChildren {
  CoachCoachRoute: typeof CoachCoachRouteWithChildren
  CoachSettingsRoute: typeof CoachSettingsRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachCoachRoute: CoachCoachRouteWithChildren,
  CoachSettingsRoute: CoachSettingsRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CoachRoute: CoachRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  CoachLoginRoute: CoachLoginRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
