/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachSettingsRouteImport } from './routes/_coach/settings'
import { Route as CoachCoachRouteImport } from './routes/_coach/coach'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComprehensiveReportRouteImport } from './routes/_authenticated/comprehensive-report'
import { Route as AuthenticatedReportSessionIdRouteImport } from './routes/_authenticated/report.$sessionId'
import { Route as AuthenticatedAssessmentTypeRouteImport } from './routes/_authenticated/assessment.$type'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachSettingsRoute = CoachSettingsRouteImport.update({
  id: '/_coach/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachCoachRoute = CoachCoachRouteImport.update({
  id: '/_coach/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComprehensiveReportRoute =
  AuthenticatedComprehensiveReportRouteImport.update({
    id: '/comprehensive-report',
    path: '/comprehensive-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportSessionIdRoute =
  AuthenticatedReportSessionIdRouteImport.update({
    id: '/report/$sessionId',
    path: '/report/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssessmentTypeRoute =
  AuthenticatedAssessmentTypeRouteImport.update({
    id: '/assessment/$type',
    path: '/assessment/$type',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/comprehensive-report': typeof AuthenticatedComprehensiveReportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/coach': typeof CoachCoachRoute
  '/settings': typeof CoachSettingsRoute
  '/assessment/$type': typeof AuthenticatedAssessmentTypeRoute
  '/report/$sessionId': typeof AuthenticatedReportSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/comprehensive-report': typeof AuthenticatedComprehensiveReportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/coach': typeof CoachCoachRoute
  '/settings': typeof CoachSettingsRoute
  '/assessment/$type': typeof AuthenticatedAssessmentTypeRoute
  '/report/$sessionId': typeof AuthenticatedReportSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/comprehensive-report': typeof AuthenticatedComprehensiveReportRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_coach/coach': typeof CoachCoachRoute
  '/_coach/settings': typeof CoachSettingsRoute
  '/_authenticated/assessment/$type': typeof AuthenticatedAssessmentTypeRoute
  '/_authenticated/report/$sessionId': typeof AuthenticatedReportSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/comprehensive-report'
    | '/dashboard'
    | '/coach'
    | '/settings'
    | '/assessment/$type'
    | '/report/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/comprehensive-report'
    | '/dashboard'
    | '/coach'
    | '/settings'
    | '/assessment/$type'
    | '/report/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/comprehensive-report'
    | '/_authenticated/dashboard'
    | '/_coach/coach'
    | '/_coach/settings'
    | '/_authenticated/assessment/$type'
    | '/_authenticated/report/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  CoachCoachRoute: typeof CoachCoachRoute
  CoachSettingsRoute: typeof CoachSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_coach/settings': {
      id: '/_coach/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof CoachSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_coach/coach': {
      id: '/_coach/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comprehensive-report': {
      id: '/_authenticated/comprehensive-report'
      path: '/comprehensive-report'
      fullPath: '/comprehensive-report'
      preLoaderRoute: typeof AuthenticatedComprehensiveReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/report/$sessionId': {
      id: '/_authenticated/report/$sessionId'
      path: '/report/$sessionId'
      fullPath: '/report/$sessionId'
      preLoaderRoute: typeof AuthenticatedReportSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assessment/$type': {
      id: '/_authenticated/assessment/$type'
      path: '/assessment/$type'
      fullPath: '/assessment/$type'
      preLoaderRoute: typeof AuthenticatedAssessmentTypeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedComprehensiveReportRoute: typeof AuthenticatedComprehensiveReportRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAssessmentTypeRoute: typeof AuthenticatedAssessmentTypeRoute
  AuthenticatedReportSessionIdRoute: typeof AuthenticatedReportSessionIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedComprehensiveReportRoute: AuthenticatedComprehensiveReportRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAssessmentTypeRoute: AuthenticatedAssessmentTypeRoute,
  AuthenticatedReportSessionIdRoute: AuthenticatedReportSessionIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  CoachCoachRoute: CoachCoachRoute,
  CoachSettingsRoute: CoachSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
