/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FullyResourcedRouteImport } from './routes/fully-resourced'
import { Route as CoachRouteImport } from './routes/_coach'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachLoginRouteImport } from './routes/coach.login'
import { Route as CoachSettingsRouteImport } from './routes/_coach/settings'
import { Route as CoachCoachRouteImport } from './routes/_coach/coach'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCycleRouteImport } from './routes/_authenticated/cycle'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedCheckoutIndexRouteImport } from './routes/_authenticated/checkout.index'
import { Route as AuthenticatedReportSessionIdRouteImport } from './routes/_authenticated/report.$sessionId'
import { Route as AuthenticatedGuideSection2RouteImport } from './routes/_authenticated/guide.section-2'
import { Route as AuthenticatedGuideSection1RouteImport } from './routes/_authenticated/guide.section-1'
import { Route as AuthenticatedCheckoutActivatingRouteImport } from './routes/_authenticated/checkout.activating'
import { Route as AuthenticatedAssessmentTypeRouteImport } from './routes/_authenticated/assessment.$type'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as CoachCoachAssesseeUserIdRouteImport } from './routes/_coach/coach.assessee.$userId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FullyResourcedRoute = FullyResourcedRouteImport.update({
  id: '/fully-resourced',
  path: '/fully-resourced',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/_coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachLoginRoute = CoachLoginRouteImport.update({
  id: '/coach/login',
  path: '/coach/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachSettingsRoute = CoachSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CoachRoute,
} as any)
const CoachCoachRoute = CoachCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => CoachRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCycleRoute = AuthenticatedCycleRouteImport.update({
  id: '/cycle',
  path: '/cycle',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutIndexRoute =
  AuthenticatedCheckoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCheckoutRoute,
  } as any)
const AuthenticatedReportSessionIdRoute =
  AuthenticatedReportSessionIdRouteImport.update({
    id: '/report/$sessionId',
    path: '/report/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGuideSection2Route =
  AuthenticatedGuideSection2RouteImport.update({
    id: '/guide/section-2',
    path: '/guide/section-2',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGuideSection1Route =
  AuthenticatedGuideSection1RouteImport.update({
    id: '/guide/section-1',
    path: '/guide/section-1',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutActivatingRoute =
  AuthenticatedCheckoutActivatingRouteImport.update({
    id: '/activating',
    path: '/activating',
    getParentRoute: () => AuthenticatedCheckoutRoute,
  } as any)
const AuthenticatedAssessmentTypeRoute =
  AuthenticatedAssessmentTypeRouteImport.update({
    id: '/assessment/$type',
    path: '/assessment/$type',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoachCoachAssesseeUserIdRoute =
  CoachCoachAssesseeUserIdRouteImport.update({
    id: '/assessee/$userId',
    path: '/assessee/$userId',
    getParentRoute: () => CoachCoachRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fully-resourced': typeof FullyResourcedRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/checkout': typeof AuthenticatedCheckoutRouteWithChildren
  '/cycle': typeof AuthenticatedCycleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/coach': typeof CoachCoachRouteWithChildren
  '/settings': typeof CoachSettingsRoute
  '/coach/login': typeof CoachLoginRoute
  '/assessment/$type': typeof AuthenticatedAssessmentTypeRoute
  '/checkout/activating': typeof AuthenticatedCheckoutActivatingRoute
  '/guide/section-1': typeof AuthenticatedGuideSection1Route
  '/guide/section-2': typeof AuthenticatedGuideSection2Route
  '/report/$sessionId': typeof AuthenticatedReportSessionIdRoute
  '/checkout/': typeof AuthenticatedCheckoutIndexRoute
  '/coach/assessee/$userId': typeof CoachCoachAssesseeUserIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fully-resourced': typeof FullyResourcedRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/cycle': typeof AuthenticatedCycleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/coach': typeof CoachCoachRouteWithChildren
  '/settings': typeof CoachSettingsRoute
  '/coach/login': typeof CoachLoginRoute
  '/assessment/$type': typeof AuthenticatedAssessmentTypeRoute
  '/checkout/activating': typeof AuthenticatedCheckoutActivatingRoute
  '/guide/section-1': typeof AuthenticatedGuideSection1Route
  '/guide/section-2': typeof AuthenticatedGuideSection2Route
  '/report/$sessionId': typeof AuthenticatedReportSessionIdRoute
  '/checkout': typeof AuthenticatedCheckoutIndexRoute
  '/coach/assessee/$userId': typeof CoachCoachAssesseeUserIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_coach': typeof CoachRouteWithChildren
  '/fully-resourced': typeof FullyResourcedRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRouteWithChildren
  '/_authenticated/cycle': typeof AuthenticatedCycleRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_coach/coach': typeof CoachCoachRouteWithChildren
  '/_coach/settings': typeof CoachSettingsRoute
  '/coach/login': typeof CoachLoginRoute
  '/_authenticated/assessment/$type': typeof AuthenticatedAssessmentTypeRoute
  '/_authenticated/checkout/activating': typeof AuthenticatedCheckoutActivatingRoute
  '/_authenticated/guide/section-1': typeof AuthenticatedGuideSection1Route
  '/_authenticated/guide/section-2': typeof AuthenticatedGuideSection2Route
  '/_authenticated/report/$sessionId': typeof AuthenticatedReportSessionIdRoute
  '/_authenticated/checkout/': typeof AuthenticatedCheckoutIndexRoute
  '/_coach/coach/assessee/$userId': typeof CoachCoachAssesseeUserIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fully-resourced'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/checkout'
    | '/cycle'
    | '/dashboard'
    | '/performance'
    | '/profile'
    | '/coach'
    | '/settings'
    | '/coach/login'
    | '/assessment/$type'
    | '/checkout/activating'
    | '/guide/section-1'
    | '/guide/section-2'
    | '/report/$sessionId'
    | '/checkout/'
    | '/coach/assessee/$userId'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fully-resourced'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/cycle'
    | '/dashboard'
    | '/performance'
    | '/profile'
    | '/coach'
    | '/settings'
    | '/coach/login'
    | '/assessment/$type'
    | '/checkout/activating'
    | '/guide/section-1'
    | '/guide/section-2'
    | '/report/$sessionId'
    | '/checkout'
    | '/coach/assessee/$userId'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_coach'
    | '/fully-resourced'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/_authenticated/checkout'
    | '/_authenticated/cycle'
    | '/_authenticated/dashboard'
    | '/_authenticated/performance'
    | '/_authenticated/profile'
    | '/_coach/coach'
    | '/_coach/settings'
    | '/coach/login'
    | '/_authenticated/assessment/$type'
    | '/_authenticated/checkout/activating'
    | '/_authenticated/guide/section-1'
    | '/_authenticated/guide/section-2'
    | '/_authenticated/report/$sessionId'
    | '/_authenticated/checkout/'
    | '/_coach/coach/assessee/$userId'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CoachRoute: typeof CoachRouteWithChildren
  FullyResourcedRoute: typeof FullyResourcedRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  CoachLoginRoute: typeof CoachLoginRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fully-resourced': {
      id: '/fully-resourced'
      path: '/fully-resourced'
      fullPath: '/fully-resourced'
      preLoaderRoute: typeof FullyResourcedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_coach': {
      id: '/_coach'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/login': {
      id: '/coach/login'
      path: '/coach/login'
      fullPath: '/coach/login'
      preLoaderRoute: typeof CoachLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_coach/settings': {
      id: '/_coach/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof CoachSettingsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/_coach/coach': {
      id: '/_coach/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachCoachRouteImport
      parentRoute: typeof CoachRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cycle': {
      id: '/_authenticated/cycle'
      path: '/cycle'
      fullPath: '/cycle'
      preLoaderRoute: typeof AuthenticatedCycleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/': {
      id: '/_authenticated/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof AuthenticatedCheckoutIndexRouteImport
      parentRoute: typeof AuthenticatedCheckoutRoute
    }
    '/_authenticated/report/$sessionId': {
      id: '/_authenticated/report/$sessionId'
      path: '/report/$sessionId'
      fullPath: '/report/$sessionId'
      preLoaderRoute: typeof AuthenticatedReportSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guide/section-2': {
      id: '/_authenticated/guide/section-2'
      path: '/guide/section-2'
      fullPath: '/guide/section-2'
      preLoaderRoute: typeof AuthenticatedGuideSection2RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guide/section-1': {
      id: '/_authenticated/guide/section-1'
      path: '/guide/section-1'
      fullPath: '/guide/section-1'
      preLoaderRoute: typeof AuthenticatedGuideSection1RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/activating': {
      id: '/_authenticated/checkout/activating'
      path: '/activating'
      fullPath: '/checkout/activating'
      preLoaderRoute: typeof AuthenticatedCheckoutActivatingRouteImport
      parentRoute: typeof AuthenticatedCheckoutRoute
    }
    '/_authenticated/assessment/$type': {
      id: '/_authenticated/assessment/$type'
      path: '/assessment/$type'
      fullPath: '/assessment/$type'
      preLoaderRoute: typeof AuthenticatedAssessmentTypeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_coach/coach/assessee/$userId': {
      id: '/_coach/coach/assessee/$userId'
      path: '/assessee/$userId'
      fullPath: '/coach/assessee/$userId'
      preLoaderRoute: typeof CoachCoachAssesseeUserIdRouteImport
      parentRoute: typeof CoachCoachRoute
    }
  }
}

interface AuthenticatedCheckoutRouteChildren {
  AuthenticatedCheckoutActivatingRoute: typeof AuthenticatedCheckoutActivatingRoute
  AuthenticatedCheckoutIndexRoute: typeof AuthenticatedCheckoutIndexRoute
}

const AuthenticatedCheckoutRouteChildren: AuthenticatedCheckoutRouteChildren = {
  AuthenticatedCheckoutActivatingRoute: AuthenticatedCheckoutActivatingRoute,
  AuthenticatedCheckoutIndexRoute: AuthenticatedCheckoutIndexRoute,
}

const AuthenticatedCheckoutRouteWithChildren =
  AuthenticatedCheckoutRoute._addFileChildren(
    AuthenticatedCheckoutRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRouteWithChildren
  AuthenticatedCycleRoute: typeof AuthenticatedCycleRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAssessmentTypeRoute: typeof AuthenticatedAssessmentTypeRoute
  AuthenticatedGuideSection1Route: typeof AuthenticatedGuideSection1Route
  AuthenticatedGuideSection2Route: typeof AuthenticatedGuideSection2Route
  AuthenticatedReportSessionIdRoute: typeof AuthenticatedReportSessionIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRouteWithChildren,
  AuthenticatedCycleRoute: AuthenticatedCycleRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAssessmentTypeRoute: AuthenticatedAssessmentTypeRoute,
  AuthenticatedGuideSection1Route: AuthenticatedGuideSection1Route,
  AuthenticatedGuideSection2Route: AuthenticatedGuideSection2Route,
  AuthenticatedReportSessionIdRoute: AuthenticatedReportSessionIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CoachCoachRouteChildren {
  CoachCoachAssesseeUserIdRoute: typeof CoachCoachAssesseeUserIdRoute
}

const CoachCoachRouteChildren: CoachCoachRouteChildren = {
  CoachCoachAssesseeUserIdRoute: CoachCoachAssesseeUserIdRoute,
}

const CoachCoachRouteWithChildren = CoachCoachRoute._addFileChildren(
  CoachCoachRouteChildren,
)

interface CoachRouteChildren {
  CoachCoachRoute: typeof CoachCoachRouteWithChildren
  CoachSettingsRoute: typeof CoachSettingsRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachCoachRoute: CoachCoachRouteWithChildren,
  CoachSettingsRoute: CoachSettingsRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CoachRoute: CoachRouteWithChildren,
  FullyResourcedRoute: FullyResourcedRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  CoachLoginRoute: CoachLoginRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
