-- Leaders Edge redemption codes.
--
-- Rich hands single-use codes to his Leaders Edge members so they can redeem 3
-- months of full access for free (100% off for 3 months, then the normal $97/mo
-- once the coupon expires). Codes are generated by coaches from the admin page.
--
-- Single-use is the point: a code is permanently consumed the moment a redeemer
-- opens the payment form (see createLeadersEdgeCheckout), so a leaked code can
-- only ever start ONE checkout. The webhook later stamps who redeemed it.
--
-- All writes go through service-role server functions (generate, validate,
-- consume, stamp). RLS is enabled with a coach-only SELECT policy so the admin
-- list can read it; there are no anon/authenticated write policies, so the only
-- way to create or burn a code is the trusted server path.

CREATE TABLE IF NOT EXISTS public.redemption_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT NOT NULL UNIQUE,
  campaign TEXT NOT NULL DEFAULT 'leaders_edge',
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- Set the instant the code is consumed (checkout form opened). Non-null = used.
  used_at TIMESTAMPTZ,
  -- Stamped by the webhook once payment completes, for the admin list.
  redeemed_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  redeemed_by_email TEXT,
  -- The Stripe Checkout Session that consumed the code (audit trail).
  stripe_session_id TEXT
);

CREATE INDEX IF NOT EXISTS redemption_codes_campaign_idx
  ON public.redemption_codes (campaign, created_at DESC);

ALTER TABLE public.redemption_codes ENABLE ROW LEVEL SECURITY;

-- Coaches can read the code list from the admin page (via the anon key + their
-- JWT). No client write policies: generation and consumption are service-role
-- only, so codes can't be minted or burned from the browser.
DROP POLICY IF EXISTS "coaches read redemption codes" ON public.redemption_codes;
CREATE POLICY "coaches read redemption codes"
  ON public.redemption_codes FOR SELECT
  USING (public.has_role(auth.uid(), 'coach'::app_role));
